# Generated by Django 3.0.4 on 2020-05-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votequestion',
            unique_together=set(),
        ),
    ]
