# Generated by Django 3.0.4 on 2020-05-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_votedown',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_voteup',
        ),
        migrations.AddField(
            model_name='answer',
            name='appreciated_answer',
            field=models.BooleanField(default=False),
        ),
    ]
