# Generated by Django 3.0.4 on 2020-05-02 10:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200502_1231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votequestion',
            unique_together={('user', 'question')},
        ),
    ]
