# Generated by Django 3.0.4 on 2020-05-02 11:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200502_1237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votequestion',
            unique_together={('question', 'user')},
        ),
    ]
