# Generated by Django 3.0.4 on 2020-05-02 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200502_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voteup',
            field=models.ManyToManyField(blank=True, related_name='voteup', to=settings.AUTH_USER_MODEL),
        ),
    ]
