# Generated by Django 3.0.4 on 2020-05-03 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_question_voteup'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votedown',
            field=models.ManyToManyField(blank=True, related_name='votedown', to=settings.AUTH_USER_MODEL),
        ),
    ]
