# Generated by Django 3.0.4 on 2020-05-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_question_votedown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votesscore',
        ),
    ]
