# Generated by Django 3.0.4 on 2020-05-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_question_votesscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteQuestion',
        ),
    ]
